<?php

/**
 * @file
 * comstack_pm.module
 */

include_once __DIR__ . '/includes/comstack_pm.devel.inc';
include_once __DIR__ . '/includes/comstack_pm.entity.inc';
include_once __DIR__ . '/includes/comstack_pm.forms.inc';

/**
 * Implements hook_filter_default_formats().
 */
function comstack_pm_filter_default_formats() {
  $formats = array();

  $formats['cs_pm'] = array(
    'format' => 'cs_pm',
    'name' => 'Comstack Private Messaging',
    'cache' => 1,
    'status' => 1,
    'weight' => 0,
    'filters' => array(
      'filter_htmlcorrector' => array(
        'weight' => -50,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_html_escape' => array(
        'weight' => -49,
        'status' => 1,
        'settings' => array(),
      ),
      'filter_url' => array(
        'weight' => -43,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_autop' => array(
        'weight' => -40,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
