<?php

/**
 * @file
 * comstack_pm.module
 */

// All logic relating to how this module specifically operates will go in here.
include_once __DIR__ . '/includes/comstack_pm.comstack_pm.inc';
// Other stuffs.
// Devel.
include_once __DIR__ . '/includes/comstack_pm.devel.inc';
// Drush rebuild commands.
include_once __DIR__ . '/includes/comstack_pm.drush.inc';
// Entity info, metadata info and load callbacks.
include_once __DIR__ . '/includes/comstack_pm.entity.inc';
// Form builder callbacks, including validate, alters and submits.
include_once __DIR__ . '/includes/comstack_pm.forms.inc';

/**
 * Implements hook_permission().
 */
function comstack_pm_permission() {
  $permissions = array(
    'bypass comstack_pm access checks' => array(
      'title' => t('Bypass conversation &amp; message access checks'),
      'description' => t('Allows a user to perform any operations against conversations and messages, with exception of view deleted conversations &amp; messages.'),
    ),
    'view deleted comstack conversations' => array(
      'title' => t('View conversations which have been marked as deleted'),
      'description' => t('Allows users to view conversations which have been marked as deleted.'),
      'restrict access' => TRUE,
    ),
    'start new comstack conversations' => array(
      'title' => t('Start new conversations'),
      'description' => t('Allows users to start new conversations with each-other.'),
    ),
    'delete leave comstack conversation' => array(
      'title' => t('Delete/Leave a conversation'),
      'description' => t("Allows users to leave conversations. It wouldn't appear in their inbox, but other participants retain it. Only people who are participants in the conversation can delete it."),
    ),
    'invite users to a comstack conversation' => array(
      'title' => t('Invite users to a conversation'),
      'description' => t('Allows users to invite other users who are not part of the conversation to it.'),
    ),
    'set a comstack conversations title' => array(
      'title' => t('Set a conversations title'),
      'description' => t("Allows users to set the title of conversations that they're part of."),
    ),
    'mark a comstack conversation as read' => array(
      'title' => t('Mark a conversation as read'),
      'description' => t('Allows users to mark a conversation as read. This permission allows users to reverse the action too.'),
    ),
    'mute a comstack conversation' => array(
      'title' => t('Mute a conversation'),
      'description' => t('Allows users to mute a conversation suppressing any notifications from it. This permission allows users to reverse the action too.'),
    ),
    'archive a comstack conversation' => array(
      'title' => t('Archive a conversation'),
      'description' => t('Allows users to archive a conversation. This permission allows users to reverse the action too.'),
    ),
    'pin a comstack conversation' => array(
      'title' => t('Pin a conversation'),
      'description' => t('Allows users to pin a conversation. This permission allows users to reverse the action too.'),
    ),
    'star a comstack conversation' => array(
      'title' => t('Star a conversation'),
      'description' => t('Allows users to star a conversation. This permission allows users to reverse the action too.'),
    ),
    'reply to a comstack conversation' => array(
      'title' => t('Can reply to conversations'),
      'description' => t("Allows users to reply (post new messages) to a conversation they're part of."),
    ),
    'edit own comstack conversation messages' => array(
      'title' => t('Edit own messages in a conversation'),
      'description' => t("Allows users to edit their own messages from a conversation that they're part of."),
    ),
    'delete own comstack conversation messages' => array(
      'title' => t('Delete own messages in a conversation'),
      'description' => t("Allows users to delete their own messages from a conversation that they're part of. Whether or not they're permanently deleted is defined by settings."),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_user_preferences().
 */
function comstack_pm_user_preferences() {
  $preferences = array();

  if (variable_get('comstack_pm_preferences__enabled__provide', FALSE)) {
    $preferences['comstack_pm_enabled'] = array(
      'title' => t('Comstack Private Messaging - Enabled'),
      'default_value' => variable_get('comstack_pm_preferences__enabled__default', 0),
      'form_ids' => array('user_profile_form'),
      'form_item' => array(
        '#title' => t('Allow people to send me private messages'),
        '#description' => t("When enabled, people can send you private messages. If you disable this they won't be able to contact you, but any existing conversations will remain unless you choose to delete them."),
        '#type' => 'checkbox',
        '#weight' => 1,
      ),
    );
  }

  return $preferences;
}
