<?php

/**
 * @file
 * comstack_pm_rest_api.module
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function comstack_pm_rest_api_ctools_plugin_directory($module, $plugin) {
  if ($module === 'restful') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_entity_property_info_alter().
 */
function comstack_pm_rest_api_entity_property_info_alter(&$info) {
  // If the picture property doesn't exist on the user entity then add it.
  // This issue has a patch to correct the problem.
  // https://www.drupal.org/node/2224645#comment-10161298
  // This module will only take care of "view".
  if (!isset($info['user']['properties']['picture'])) {
    $info['user']['properties']['picture'] = array(
      'label' => t('Picture'),
      'description' => t("The user's picture."),
      'type' => 'file',
      'access callback' => 'comstack_pm_rest_api_user_access_picture_property',
      'getter callback' => 'comstack_pm_rest_api_user_get_picture_property',
      'schema field' => 'picture',
    );
  }
}

/**
 * Access callback for the picture property.
 */
function comstack_pm_rest_api_user_access_picture_property($op, $property, $entity = NULL, $account = NULL) {
  if ($op === 'view') {
    return TRUE;
  }
}

/**
 * Picture property get callback.
 */
function comstack_pm_rest_api_user_get_picture_property($account, array $options, $name, $entity_type) {
  // Check for an image object and load a default if one exists.
  if (empty($account->picture)) {
    $account->picture = comstack_pm_rest_api_user_get_default_picture();
  }

  return empty($account->picture) ? NULL : $account->picture;
}

/**
 * Return a file object for a default avatar or NULL of one doesn't exist.
 */
function comstack_pm_rest_api_user_get_default_picture() {
  static $_comstack_pm_rest_api_user_default_picture;

  if (!isset($_comstack_pm_rest_api_user_default_picture)) {
    $default_avatar_path = variable_get('user_picture_default', '');

    if ($default_avatar_path && file_valid_uri($default_avatar_path)) {
      $file = new stdClass();
      $file->uri = $default_avatar_path;

      $_comstack_pm_rest_api_user_default_picture = $file;
    }
    else {
      $_comstack_pm_rest_api_user_default_picture = NULL;
    }
  }

  return $_comstack_pm_rest_api_user_default_picture;
}
